{
    'name': 'La Clinique Extension',
    'version': '14.0.1',
    'category': '',
    'summary': 'La Clinique Extension',
    
    'author': 'SSL',
    'website': '',
    'maintainer': '',

    'depends': ['base','sale','account','product','purchase', 'stock'],
    'data': [
        'data/mail_template.xml',
        'data/ir_cron_data.xml',
        'security/ir.model.access.csv',
        'views/api_logs.xml',
        'views/doctor_details.xml',
        'views/location_view.xml',
        'views/journal.xml',
        'views/product_pricelist.xml',
        'views/insurance_provider.xml',
        'views/bin_location_view.xml',
        'views/product_profile_view.xml',
        'views/partner.xml',
        'views/product.xml',
        'views/sale_view.xml',
        'views/purchase.xml',
        'views/invoice.xml',
        'views/account_payment.xml',
        'views/picking_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'price': 110.00,
    'currency': 'EUR',
    'images': ['static/description/icon.png'],
    'license': 'AGPL-3',
}
